services:
  - type: web
    name: klaro-backend
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_API_URL
        value: https://openrouter.ai/api/v1/chat/completions
      - key: AI_MAX_TOKENS
        value: 3072

databases:
  - name: klaro-db
    plan: starter